const actionType={
    GET_HOME : 'GET_HOME',
    GET_CURRENT_SONG: 'GET_CURRENT_SONG',
    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
    PLAY: 'PLAY',
    SET_LIST_SONGS_IN_ALBUM: 'SET_LIST_SONGS_IN_ALBUM',
    UPDATE_CURRENT_SONG_IN_ALBUM: 'UPDATE_CURRENT_SONG_IN_ALBUM',
    SET_SONG:'SET_SONG',
    SET_SHUFFLE_SONGS_IN_ALBUM:'SET_SHUFFLE_SONGS_IN_ALBUM',
    SET_LOOP: 'SET_LOOP',
    SET_PLAYLIST:'SET_PLAYLIST',
    SET_EVENTS:'SET_EVENTS',
    SET_CHART:'SET_CHART',
    PUST_SONG_TO_HISTORY:'PUST_SONG_TO_HISTORY',
    UPDATE_POSITION_OF_SONG:'UPDATE_POSITION_OF_SONG',
    SET_DATA_SEARCH:'SET_DATA_SEARCH',
    SET_CURRENT_PAGE:'SET_CURRENT_PAGE',
    SET_CURRENT_URL:'SET_CURRENT_URL',
}

export default actionType