const actionType={
    GET_HOME : 'GET_HOME',
    GET_CURRENT_SONG: 'GET_CURRENT_SONG',
    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
    PLAY: 'PLAY',
    SET_LIST_SONGS_IN_ALBUM: 'SET_LIST_SONGS_IN_ALBUM',
    UPDATE_CURRENT_SONG_IN_ALBUM: 'UPDATE_CURRENT_SONG_IN_ALBUM',
    SET_SONG:'SET_SONG',
    SET_SHUFFLE_SONGS_IN_ALBUM:'SET_SHUFFLE_SONGS_IN_ALBUM',
    SET_LOOP: 'SET_LOOP',
    SET_PLAYLIST:'SET_PLAYLIST',
}

export default actionType